name: Build project
on: [push, pull_request]
jobs:
  build-jdk8:
    runs-on: ubuntu-latest
    name: Build with Java 8
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-jdk8-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-jdk8-
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Maven verify
        run: mvn -B verify
#  build-jdk11:
#    runs-on: ubuntu-latest
#    name: Build with Java 11
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/cache@v1
#        with:
#          path: ~/.m2/repository
#          key: ${{ runner.os }}-maven-jdk11-${{ hashFiles('**/pom.xml') }}
#          restore-keys: |
#            ${{ runner.os }}-maven-jdk11-
#      - name: Set up JDK 11
#        uses: actions/setup-java@v1
#        with:
#          java-version: 11
#      - name: Maven verify
#        run: mvn -B verify